# Static build version - changing the version dynamically means you can't
# just click from github to see how things are progressing until the build has
# finished, which could be a bit annoying.
version: 1.{build}-{branch}

environment:
  matrix:
    - platform: x64
      target: AppVeyor
      visualstudio_string: vs2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

matrix:
  fast_finish: true

init:
  # Use CRLF line endings on Windows so users can just use Notepad.
  - git config --global core.autocrlf true

install:
  - git submodule update --init --recursive
  - iwr -useb get.scoop.sh | iex
  - scoop install llvm nasm

build_script:
  - cmake --version
  - cmake .

after_build:
  - echo "woo"

test: off
