# Static build version - changing the version dynamically means you can't
# just click from github to see how things are progressing until the build has
# finished, which could be a bit annoying.

# Good Reference - https://chromium.googlesource.com/external/github.com/google/googletest/+/refs/heads/master/appveyor.yml
version: 1.{build}-{branch}

environment:
  matrix:
    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      NEXT_DIR: "%APPVEYOR_BUILD_FOLDER%"

matrix:
  fast_finish: true

init:
  # Use CRLF line endings on Windows so users can just use Notepad.
  - git config --global core.autocrlf true
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - git submodule update --init --recursive
  - ps: iwr -useb get.scoop.sh | iex
  - scoop install llvm nasm

build_script:
  - cmake --version
  - mkdir build && cd ./build
  - cmake -G "NMake Makefiles" -DCMAKE_CONFIGURATION_TYPES=Debug ..
  - nmake install
  # - cmake --build . --config Debug -- /m

after_build:
  - ls ..
  - ls .
  - ps: "& './build/test/goalc-test.exe'"

test: off
